services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/ # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3001:3000
    container_name: todo-frontend
  server:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: server
  mongo:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: mongo
  redis:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: redis
  nginx:
    image: nginx:1.23.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server